preApp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view()),
]

preApp/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.Registration.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

preApp/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone

# Create your models here.

class UserManager(BaseUserManager):

    def _create_user(self, id, password, email, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError("User must have an E-mail")
        now = timezone.localtime()
        email = self.normalize_email(email)
        user = self.model(
            id = id,
            is_staff = is_staff,
            is_superuser = is_superuser,
            last_login = now,
            date_joined = now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, id, email, password, **extra_fields):
        return self._create_user(id, email, password, False, False, **extra_fields)
    
    def create_superuser(self, id, email, password, **extra_fields):
        return self._create_user(id, email, password, True, True, **extra_fields)
    

class User(AbstractUser):
    username = None
    id = models.CharField(unique=True, max_length=155)
    email = models.EmailField(unique=True, max_length=155)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    USERNAME_FIELD = 'id'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()

preApp/user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms

User = get_user_model()

# class RegisterForm(UserCreationForm):

#     class Meta:
#         model = User
#         fields = [ 'id']

class LoginForm(AuthenticationForm):

    class Meta:
        medel = User
        fields = [ 'id', 'password']
        

class RegisterForm(forms.ModelFrom):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    passwordck = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['id', 'nickname', 'email', 'password']

    def clean_password2(self):
        cd = self.cleand_data
        if cd['password'] != cd ['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

preApp/user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm


from .forms import RegisterForm, LoginForm


# Create your views here.


class register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_neser' : new_user})
        user_form = RegisterForm()

    return render(request, 'registraion/register.html')

class Registration(View):
    def get(self, request):
        pass
    def post(self, request):
        pass


class Login(View):
    def get(self, request):
        pass
    def post(self, request):
        pass


class Logout(View):
    def get(self, request):
        pass
    def post(self, request):
        pass

preApp/user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>유저</title>
</head>
<body>
    <div class="container">
        <h1>User</h1>
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

preApp/user/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
  로그인
{% endblock title %}

{% block content %}
{% comment %}
  
<h2>로그인 페이지</h2>
<form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
</form>
{% endcomment %}

<div class="row">
    <div class="col-md2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">Please enter your login informations.</div>
    </div>
    <form action="" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="login" class="btn btn-primary">
    </form>
    <div class="col-md-2"></div>
</div>


{% endblock %}

preApp/user/templates/user/logout.html
{% extends "base.html" %}
{% block title %}
  Logdout
{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">You have benn successfully logged out.</div>
        <a href="{% url 'user:login' %}" class="btn btn-primary">Click ot Login</a>
    </div>
    <div class="col-md-2"></div>
  </div>
{% endblock content %}

preApp/user/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
<h2>회원가입 페이지</h2>
<form action="{% url 'user:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>


{% endblock %}

preApp/user/templates/user/user_register.html
{% extends 'base.html' %}

{% block content %}
<h2>회원가입 페이지</h2>
<form action="{% url 'user:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>


{% endblock %}