preApp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view()),
]

preApp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), 
    # 글 상세 조회
    path("detail/<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.PostCreateView.as_view(), name='write'),
    # 글 수정
    path("delete/<int:pk>/edit/", views.PostUpdateView.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/delete/", views.PostDeleteView.as_view(), name='delete'),
    # 글 검색
    path("search/<str:tag>/", views.Index.as_view(), name='list_srch'),
    # 코멘트 작성
    # path("detail/<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    # 코멘트 삭제
    # path("detail/<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    # 태그 작성
    # path("detail/<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    # 태그 삭제
    # path("detail/<int:pk>/", views.PostDetailView.as_view(), name='detail'),
]

preApp/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.Registration.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

preApp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.SET_DEFAULT, default=1)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:10]
    

class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

preApp/blog/forms.py
from django import forms
from .models import Post, Comment, HashTag, Category

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = [ 'title', 'content', 'category','writer' ]

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = [ 'content']
        widgets = {
            'content' : forms.Textarea(attrs = {'rows' : '3', 'cols' : '30'})
        }

class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = [ 'name' ]

class Category(forms.ModelForm):

    class Meta:
        model = Category
        fields = [ 'name' ]

preApp/blog/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse

# Create your views here.

class Index(View):
    def get(self, request):
        post_objs = Post.objects.all()
        context = {
            "posts" : post_objs,
            "title" : "Blog"
        }

        return render(request, 'blog/post_list.html', context)
    
class PostListView(ListView):
    model = Post
    context_object_name = 'post_list'

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:list')

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.all()
        context['hashtags'] = HashTag.objects.all()
        return context


class PostUpdateView(UpdateView):
    model = Post
    context_object_name = 'post_update'
    form_class = PostForm
    success_url = reverse_lazy('blog:list')


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')

preApp/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>
        {% block title %}
          {{ title }}
        {% endblock title %}
    </title>{{ title }}
</head>
<body>
    <div class="container">
        <h1>blog</h1>
        {% block JSscript %}
          
        {% endblock JSscript %}
        {% block content %}
          
        {% endblock content %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

preApp/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h2>{% trans "Title :" %} {{ post.title }}</h2>
  {% comment %}
    
  {% if post_writer == request.user %}
    <a href="{% url 'blog:edit' pk=post_id %}" class="btn">{% trans "수정" %}</a>
    <form action="{% url 'blog:delete' pk=post_id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="{% trans 'Delete' %}" class="btn">
    </form>
  {% endif %}
  {% endcomment %}
  <a href="{% url 'blog:edit' pk=post.id %}" class="btn">{% trans "수정" %}</a>
  <form action="{% url 'blog:delete' pk=post.id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="{% trans 'Delete' %}" class="btn">
  </form>

    <p>{% trans 'Content:' %} {{ post.content }}</p>
    <p>{% trans 'Writer:' %} {{ post.writer }}</p>
    <p>{% trans 'Date:' %} {{ post.update_at }}</p>

    <br><br>
    여기 아래는 댓글
    {% if comments %}
      <ul>
        {% for comment in comments %}
            <li>{{ comment.content }} </li>
      {% endfor %}
      </ul>
    {% else %}
      <p>현재 댓글이 달려있지 않습니다.</p>
    {% endif %}
    <a href="url 'blog:cm-write' pk=post.id" class="btn">댓글 추가</a>

    <br><br>
    여기 아래는 태그
    {% if hashtags %}
      <ul>
        {% for hashtag in hashtags %}
          {% if hashtag.post_id == post.id %}
            <li>{{ hashtag.name }} </li>
          {% endif %}
      {% endfor %}
      </ul>
    {% else %}
      <p>현재 태그가 달려있지 않습니다.</p>
    {% endif %}
    <a href="url 'blog:tag-write' pk=post.id" class="btn">태그 추가</a>
{% endblock content %}

preApp/blog/templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
<h3>수정을 해봅시다</h3>
<form action="{% url 'blog:edit' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
</form>
{% endblock content %}

preApp/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% block JSscript %}
  
{% endblock JSscript %}
{% block content %}
<form action="{% url 'blog:write' %}" method="post" id="textbox">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-success">
</form>
{% endblock content %}

preApp/blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
  <p class="main-title">블로그 게시판의 첫 화면</p>
  {% if posts %}
    <table class="table">
        <thead class="table-light">
            <tr>
                <td>제목</td>
                <td>작성자</td>
                <td>작성일자</td>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
              <tr>
                <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                <td>{{ post.writer }}</td>
                <td>{{ post.update_at }}</td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
  {% else %}
    <h1>현재 작성된 글이 없습니다.</h1>
  {% endif %}
  <form action="{% url 'blog:write' %}" method="get">
    <input type="hidden" name="'{{ redirect_field_name }}" value="{{ request.GET.next }}">
    <input type="submit" value="글 작성">
  </form>
  <form action="{% url 'user:logout' %}" method="post">
    <input type="submit" value="로그아웃">
  </form>
{% endblock content %}

preApp/blog/templates/blog/write.html
{% extends "blog/base.html" %}

{% block content %}
  <h1>글 작성</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="text">
  </form>
{% endblock content %}